### ISSUE TITLE
Crashing on startup with 1.7.2 1.1.1.3 and 1.1.1.4 but not earier versions

### ISSUE THREAD

**Issue by RafaelFuchs** [Zarathul/simplefluidtanks#3]
All other 1.7.2 versions work fine.
Crash report given:
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/30/14 4:40 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: cpw/mods/fml/client/event/ConfigChangedEvent$OnConfigChangedEvent
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:514)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:815)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: cpw/mods/fml/client/event/ConfigChangedEvent$OnConfigChangedEvent
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
    at java.lang.Class.privateGetPublicMethods(Unknown Source)
    at java.lang.Class.getMethods(Unknown Source)
    at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:47)
    at net.zarathul.simplefluidtanks.ClientProxy.preInit(ClientProxy.java:14)
    at net.zarathul.simplefluidtanks.SimpleFluidTanks.preInit(SimpleFluidTanks.java:43)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:512)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.client.event.ConfigChangedEvent$OnConfigChangedEvent
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 43 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 74776088 bytes (71 MB) / 445644800 bytes (425 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.211.1121 Minecraft Forge 10.12.2.1121 47 mods loaded, 46 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.2.211.1121} [Forge Mod Loader](forge-1.7.2-10.12.2.1121.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.12.2.1121} [Minecraft Forge](forge-1.7.2-10.12.2.1121.jar) Unloaded->Constructed->Pre-initialized
    Aroma1997Core{1.0.2.4} [Aroma1997Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.2.10} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.2.14} [Not Enough Items](NotEnoughItems-1.7.2-1.0.2.14-universal.jar) Unloaded->Constructed->Pre-initialized
    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    battlegear2{1.0.5.5} [Mine & Blade Battlegear 2 - Bullseye](1.7.2-MB_Battlegear2-Bullseye-1.0.5.5.jar) Unloaded->Constructed->Pre-initialized
    lucky{5.0.0} [Lucky Block]([1-7-2]_Lucky_Block_v5-0-0.jar) Unloaded->Constructed->Pre-initialized
    DC1{3.3.2.18} [KingCore]([1.7.2] KingCore v3.3.2.18.jar) Unloaded->Constructed->Pre-initialized
    EB{2.1.2.6} [Ender Book]([1.7.2] EnderBook v2.1.2.6.jar) Unloaded->Constructed->Pre-initialized
    CraftableAnimals{2.4.1.0} [Craftable Animals]([1.7.2]CrafrableAnimals v2.4.1.0.jar) Unloaded->Constructed->Pre-initialized
    uncraftingTable{1.4} [jglrxavpok's UncraftingTable]([1.7.2]Uncrafting Table Mod v1.4.zip) Unloaded->Constructed->Pre-initialized
    FishingNets{1.1.1.3} [Fishing Nets]([1.7.2M] FishingNets v1.1.1.3.jar) Unloaded->Constructed->Pre-initialized
    IC2{2.1.477-experimental} [IndustrialCraft 2](industrialcraft-2-2.1.477-experimental.jar) Unloaded->Constructed->Pre-initialized
    AdvancedMachines{1.0.8} [IC2 Advanced Machines Addon](AdvancedMachinesAS-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    AdvancedSolarPanel{1.7.2-3.5.0} [Advanced Solar Panels](AdvancedSolarPanel-1.7.2-3.5.0.jar) Unloaded->Constructed->Pre-initialized
    Aroma1997CoreHelper{1.0.2.4} [Aroma1997Core|Helper](Aroma1997Core-1.7.2-1.0.2.4.jar) Unloaded->Constructed->Pre-initialized
    tennox_bacteria{2.3} [Bacteria Mod](BacteriaMod-1.7.2-2.3.0.jar) Unloaded->Constructed->Pre-initialized
    BattleTowers{1.4.6} [Battle Towers](BattleTowers-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.0.16} [Baubles](Baubles-1.7.2-1.0.0.16.jar) Unloaded->Constructed->Pre-initialized
    bcmod{1.7.2 - 2.2.0} [BCMod (Brad16840.Common mod)](BCMod-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    BetterChests{1.1.1.0} [BetterChests](BetterChests-1.7.2-1.1.1.0.jar) Unloaded->Constructed->Pre-initialized
    c2c{3.0.0.0} [Coal 2 Charcoal](c2c-3.0.0.0.jar) Unloaded->Constructed->Pre-initialized
    CompactWindmills{1.0.3.1} [CompactWindmills](CompactWindmills-1.7.2-1.0.3.1.jar) Unloaded->Constructed->Pre-initialized
    DamageIndicatorsMod{3.1.1} [Damage Indicators](Damage-Indicators-Mod-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    DragonMounts{r38} [Dragon Mounts](dragonmount_r38_mc1.7.x.zip) Unloaded->Constructed->Pre-initialized
    emeraldmod{1.0} [EmeraldMod](EmeraldMod 1.7.2 Forge V3.3.3.jar) Unloaded->Constructed->Pre-initialized
    eplus{1.7.2-2.0.1.6} [Enchanting Plus](EnchantingPlus-1.7.2-2.0.1.6.jar) Unloaded->Constructed->Pre-initialized
    EnderStorage{1.4.4.8} [EnderStorage](EnderStorage-1.7.2-1.4.4.8-universal.jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.2-132.45b0b50} [Mantle](Mantle-1.7.2-0.2.8.jar) Unloaded->Constructed->Pre-initialized
    radixcore{1.2.0} [RadixCore](RadixCore-1.2.0 MC-1.7.2.zip) Unloaded->Constructed->Pre-initialized
    mca{4.0.4} [Minecraft Comes Alive](MCA-4.0.4 MC-1.7.2.zip) Unloaded->Constructed->Pre-initialized
    mythril{1.6} [Mythril mod](mithril_mod-1.7.2-1.6.jar) Unloaded->Constructed->Pre-initialized
    eastonium_modrinks{V2.02 1.7.2} [Mo' Drinks!](MoDrinks-1.7.2 - 2.02.jar) Unloaded->Constructed->Pre-initialized
    MoreEnchants{1.3.0} [MoreEnchants](MoreEnchants-MC1.7-1.3.1.jar) Unloaded->Constructed->Pre-initialized
    moreplayermodels{1.7.2} [MorePlayerModels](MorePlayerModels_1.7.2.jar) Unloaded->Constructed->Pre-initialized
    quiverchevsky{b56} [QuiverBow](QuiverBow_1.7.2_b56.zip) Unloaded->Constructed->Pre-initialized
    redgear_core{@CoreVersion@} [Red Gear Core](RedGearCore-2.1.0.jar) Unloaded->Constructed->Pre-initialized
    RedstonePasteMod{1.6} [Redstone Paste](Redstone-Paste-Mod-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    Reciper{1.2.0} [§3§oSDXC §b§oReciper (Hardcoded)](SDXC_Reciper_1.2.0.jar) Unloaded->Constructed->Pre-initialized
    simplefluidtanks{1.7.2-1.1.1.3} [Simple Fluid Tanks](simplefluidtanks-1.7.2-1.1.1.3.jar) Unloaded->Constructed->Errored
    bspkrsCore{6.9} [bspkrsCore]([1.7.2]bspkrsCore-universal-6.9.jar) Unloaded->Constructed->Pre-initialized
    TreeCapitator{1.7.2.r02} [TreeCapitator](Tree-Capitator-Mod-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    TwilightForest{2.0.3} [The Twilight Forest](twilightforest-1.7.2-2.0.3.jar) Unloaded->Constructed->Pre-initialized
    AS_UpdateCheck{1.1.5} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    XRay{v9.1} [XRay](minecraft.jar) Unloaded->Disabled
    Mantle Environment: Environment healthy.

**Comment by Zarathul** [comment]
You use a way outdated version of Forge (10.12.2.1121). You need at least 10.12.2.1145.
